name: cst

channels:
  - conda-forge
  - r

# notes R packages stats and utils were not found
dependencies:
  - python>=3.9, <3.14
  - cartopy
  - datrie # for snakemake
  - dvc
  - descartes
  - flit>=3.2
  - gcsfs>=2023.12.1
  - gdal>=3.1
  - geopandas>=0.10
  - graphviz # for snakemake
  - hydromt>=0.9.4, <1.0
  - hydromt_wflow>=0.6.0, <1.0
  - jupyter # to run examples
  - matplotlib
#  - numpy
  - pandas<3.0.0
  - pip
#  - proj
  # - r-base
  # - r-essentials
  # - r-akima
  # - r-patchwork
  # - r-doparallel
  # - r-devtools
  # - r-dplyr
  # - r-e1071
  # - r-fitdistrplus
  # - r-forecast
  # - r-ggplot2
  # - r-MASS
  # - r-ncdf4
  # - r-scales
  # - r-sf
  # - r-tibble
  # - r-tidyr
  # - r-r.utils
  # - r-yaml
  # - rpy2
  # - rtools  # only needed for windows
  - scipy<1.17
  - seaborn # plot
#  - shapely>=2.0.0
#  - tabulate==0.8.10 # snakemake dependency, bug in v0.9.0
#  - xarray<=2024.3.0
  - xclim
  - zarr
  - pip:
      - hydroengine
      - gwwapi
      - snakemake>=8.20, <9.0