model_build_config: config/defaults/wflow_build_model.yml
waterbodies_config: config/defaults/wflow_update_waterbodies.yml
wflow_outvars: ["river discharge", "groundwater recharge"]
observations_timeseries: test_case/test_data/observations_timeseries.csv
