clim_project: cmip6
models:
  - NOAA-GFDL/GFDL-ESM4
scenarios: [ssp245]
members: [r1i1p1f1]
variables:
  precip: {source: precip, canonical: rate, units: mm/day, change: relative}
  temp: {source: temp, canonical: state, units: degC, change: absolute}
historical_year_range: [1990, 2010]
future_horizons:
  far: [2070, 2090]
